#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: vir-mir
 * Date: 04.08.14
 * Time: 13:20
 */

$_SERVER['REQUEST_URI'] = '/mirgate/';
$_SERVER['DOCUMENT_ROOT'] = __DIR__ . '/www';
define('BM_CONSOLE', true);
require_once($_SERVER['DOCUMENT_ROOT'] . '/global.php');

$console = new bmConsole(array('database' => 'default'));
$console->echoText("\n");


